user_index:
    path:     /
    defaults: { _controller: UserBundle:User:index }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: UserBundle:User:new }
    methods:  [GET, POST]