sc_dashboard:
    resource: "@AdminBundle/Resources/config/routing/dashboard.yml"
    prefix:   /

sc_etudiant:
    resource: "@AdminBundle/Resources/config/routing/etudiant.yml"
    prefix:   /etudiant

sc_matiere:
    resource: "@AdminBundle/Resources/config/routing/matiere.yml"
    prefix:   /matiere