services:
    sc.manager.user:
        class: App\Score\Service\UserBundle\Manager\UserManager
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "%kernel.root_dir%"]
        public: true