etudiant_index:
    path:     /
    defaults: { _controller: "AdminBundle:Etudiant:index" }
    methods:  GET

etudiant_show:
    path:     /show/{id}
    defaults: { _controller: "AdminBundle:Etudiant:show" }
    methods:  GET

etudiant_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Etudiant:new" }
    methods:  [GET, POST]

etudiant_edit:
    path:     /edit/{id}
    defaults: { _controller: "AdminBundle:Etudiant:edit" }
    methods:  [GET, POST]

etudiant_update:
    path:     /update/{id}
    defaults: { _controller: "AdminBundle:Etudiant:update" }
    methods:  [POST, PUT]

etudiant_delete:
    path:     /delete/{id}
    defaults: { _controller: "AdminBundle:Etudiant:delete" }
    methods:  [GET, DELETE]

etudiant_generer_pdf:
    path:     /generer-pdf/{id}
    defaults: { _controller: "AdminBundle:Etudiant:genererPdf" }
    methods:  [GET, POST]
