matiere_index:
    path:     /
    defaults: { _controller: "AdminBundle:Matiere:index" }
    methods:  GET

matiere_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Matiere:new" }
    methods:  [GET, POST]

matiere_edit:
    path:     /edit/{id}
    defaults: { _controller: "AdminBundle:Matiere:edit" }
    methods:  [GET, POST]

matiere_update:
    path:     /update/{id}
    defaults: { _controller: "AdminBundle:Matiere:update" }
    methods:  [POST, PUT]

matiere_delete:
    path:     /delete/{id}
    defaults: { _controller: "AdminBundle:Matiere:delete" }
    methods:  [GET, DELETE]